# Generated by Django 4.2 on 2025-08-13 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='desc_pro',
        ),
    ]
